# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kuka_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    kuka_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

kuka_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      []
    state_interfaces:
      []
kuka_hand_controller:
  ros__parameters:
    joint: left_gripper_finger_joint